version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: pointzeroonedbuser
      POSTGRES_PASSWORD: pointzeronepassword
      POSTGRES_DB: pointzerodb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pointzeroonedbuser", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    volumes:
      - ./redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - '6379:6379'

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'

  nats:
    image: nats:latest
    environment:
      NATS_SERVER_PORT_TCP: 4222
      NATS_SERVER_PORT_UDP: 4223
    ports:
      - '4222:4222'
      - '4223:4223'

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
      MINIO_PROGRAM_NAME: minio-server
      MINIO_BROWSE_COMMAND: "mc alias set local http://localhost:9000 minioadmin minioadmin"
    volumes:
      - ./miniodata:/data
    ports:
      - '9000:9000'

  otel-collector:
    image: openzipkin/zipkin:2.18.3
    environment:
      ZIPKIN_SERVER_PORT: 9411
    ports:
      - '9411:9411'
